
"""change index on consumption_records to be unique

Revision ID: 8296d1e54123
Revises: d1edf4ba5d91
Create Date: 2025-09-09 12:10:30.394607
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8296d1e54123'
down_revision = 'd1edf4ba5d91'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumption_customer_ts'), table_name='consumption_records')
    op.create_index('ix_consumption_customer_ts', 'consumption_records', ['customer_id', 'ts'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consumption_customer_ts', table_name='consumption_records')
    op.create_index(op.f('ix_consumption_customer_ts'), 'consumption_records', ['customer_id', 'ts'], unique=False)
    # ### end Alembic commands ###