"""add invoice.created_at

Revision ID: d1edf4ba5d91
Revises: f4e5d6c7b8a9
Create Date: 2025-09-09 11:04:37.306846
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d1edf4ba5d91"
down_revision = "f4e5d6c7b8a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ux_consumption_customer_ts"), table_name="consumption_records")
    op.add_column(
        "invoices",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "created_at")
    op.create_index(
        op.f("ux_consumption_customer_ts"),
        "consumption_records",
        ["customer_id", "ts"],
        unique=True,
    )
    # ### end Alembic commands ###
