"""drop meter_code from customers

Revision ID: ebfa316f2793
Revises: 7d48833d0e21
Create Date: 2025-09-08 13:20:09.609797
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ebfa316f2793"
down_revision = "7d48833d0e21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consumption_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("kwh", sa.Float(), nullable=False),
        sa.Column("price_eur_per_kwh", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_consumption_customer_ts",
        "consumption_records",
        ["customer_id", "ts"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_records_customer_id"),
        "consumption_records",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_records_ts"), "consumption_records", ["ts"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("total_eur", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoices_customer_id"), "invoices", ["customer_id"], unique=False
    )
    # ### end Alembic commands ###

    # Insert demo customers if they don't already exist
    op.execute(
        """
    INSERT INTO customers (id, name)
    SELECT 1, 'ACME d.o.o.'
    WHERE NOT EXISTS (SELECT 1 FROM customers WHERE id=1);
    """
    )
    op.execute(
        """
    INSERT INTO customers (id, name)
    SELECT 2, 'Beta d.o.o.'
    WHERE NOT EXISTS (SELECT 1 FROM customers WHERE id=2);
    """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoices_customer_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_consumption_records_ts"), table_name="consumption_records")
    op.drop_index(
        op.f("ix_consumption_records_customer_id"), table_name="consumption_records"
    )
    op.drop_index("ix_consumption_customer_ts", table_name="consumption_records")
    op.drop_table("consumption_records")
    op.drop_table("customers")
    # ### end Alembic commands ###

    op.execute("DELETE FROM customers WHERE id IN (1,2);")
